### ISSUE TITLE
Update svgdom / svg.js fails

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/mass-tools#73] opened 2022-03-03 07:42 UTC
Currently we can not update those 2 libraries as long as we didn't update our testcases

- svgdom
- svg.js

https://github.com/svgdotjs/svg.js/issues/1252

**Comment by lpatiny** [comment] 2023-02-22 14:15
I think we should migrate to a react approach without svg libraries like in https://github.com/cheminfo/molecules-graph

**Comment by Fuzzyma** [comment] 2023-09-03 05:57
Not sure, if still relevant but the issue is fixed on master now

**Comment by lpatiny** [comment] 2023-09-04 14:46
Great many thanks !

**Closed** 2024-06-26 07:38 UTC
